# Enhanced ReID Configuration
# Intelligent track assignment with quality monitoring

# Video and output settings
video_path: inputs/horse_11.mp4
output_path: null
display: false

# Model selection
human_detector: rtdetr
horse_detector: rtdetr
human_pose_estimator: vitpose
horse_pose_estimator: superanimal

# SAM model for Enhanced ReID
sam_model: sam2

# Confidence thresholds
confidence_human_detection: 0.7
confidence_horse_detection: 0.8
confidence_human_pose: 0.5
confidence_horse_pose_superanimal: 0.5
confidence_horse_pose_vitpose: 0.5

# Basic settings
jockey_overlap_threshold: 0.4
max_frames: 
device: cuda

# ENHANCED REID PIPELINE SETTINGS
enable_reid_pipeline: true
reid_similarity_threshold: 0.3

# Track Quality Monitoring
track_stability_threshold: 0.3    # Threshold for unstable tracks (lower = more aggressive reassignment)
track_newness_threshold: 5        # Frames to consider track "new"
quality_stability_window: 10      # Window for calculating stability metrics

# Memory and Motion Settings
samurai_memory_size: 10           # Memory size for track history
motion_distance_threshold: 200    # Motion prediction threshold (pixels)

# Components
enable_depth_anything: true

# Performance Settings
max_tracks_per_frame: 11          # Limit to expected number of horses