# Clean config.yaml (removed duplicates from your version)

# Video and output settings
video_path: inputs/horse_11.mp4
output_path: null
display: false

# Model selection
human_detector: rtdetr
horse_detector: rtdetr
human_pose_estimator: vitpose
horse_pose_estimator: superanimal

# SAM model for SAMURAI tracking
sam_model: sam2

# Confidence thresholds
confidence_human_detection: 0.5
confidence_horse_detection: 0.5
confidence_human_pose: 0.5
confidence_horse_pose_superanimal: 0.5
confidence_horse_pose_vitpose: 0.5

# Basic settings
jockey_overlap_threshold: 0.4
max_frames: null
device: cuda

# SAMURAI TRACKING SETTINGS
enable_reid_pipeline: true
samurai_motion_weight: 0.5
samurai_memory_size: 22
samurai_similarity_threshold: 0.15
samurai_max_lost_frames: 25

# ReID and feature settings
reid_similarity_threshold: 0.3
reid_embedding_history_size: 15
enable_depth_anything: true
enable_megadescriptor: true

# Motion and distance settings
motion_distance_threshold: 200
acceleration_prediction: true
visual_memory_enabled: true

# Track management
max_tracks_per_frame: 15
track_consolidation_enabled: true
consolidation_similarity_threshold: 0.7

# Performance tuning
rgb_weight: 0.7
depth_weight: 0.3
depth_shape_consistency: true
consistency_bonus_threshold: 0.4