# BoostTrack + SigLIP Configuration - OPTIMIZED FOR TRACKING STABILITY
# This config addresses track fragmentation and improves ReID performance

# Basic Settings
video_path: 'inputs/horse_9.mp4'
output_path: null
display: false
device: 'cuda'
max_frames: null

# Model Selection
human_detector: 'rtdetr'
horse_detector: 'rtdetr'
human_pose_estimator: 'vitpose'
horse_pose_estimator: 'superanimal'

# Detection Confidence Thresholds (Quality-Focused - High Standards)
confidence_human_detection: 0.6      # High threshold - only confident human detections
confidence_horse_detection: 0.6      # High threshold - only confident horse detections  
confidence_human_pose: 0.5
confidence_horse_pose_superanimal: 0.5
confidence_horse_pose_vitpose: 0.5

# Tracking Method
tracker_type: 'deepocsort'

# Deep OC-SORT Configuration - KALMAN FILTER FIX
deepocsort_config:
  # === CORE TRACKING ===
  max_age: 100
  min_hits: 7                    # Reduced to 2 - minimum for Kalman stability
  det_thresh: 0.7
  iou_threshold: 0.2
  per_class: false
  
  # === KALMAN FILTER STABILITY ===
  delta_t: 1                     # Single frame velocity
  inertia: 0.05                   # Reduced inertia - less history dependence
  Q_xy_scaling: 1              # Higher noise tolerance
  Q_s_scaling: 0.5               # Higher scale noise tolerance
  
  # === ASSOCIATION ===
  asso_func: "iou"
  w_association_emb: 0.8
  alpha_fixed_emb: 0.7           # Faster embedding updates
  aw_param: 0.3
  
  # === DISABLE PROBLEMATIC FEATURES ===
  embedding_off: true
  cmc_off: true                  # Disable camera motion compensation
  aw_off: true                   # Disable adaptive weighting

# SigLIP Classification (Quality-Focused Configuration)
enable_siglip_classification: true
reference_folder_path: 'inputs/ref_imgs/'
max_horses: 9                     # Reduced expectation - focus on quality
max_jockeys: 9                    # Reduced expectation - focus on quality  
siglip_confidence_threshold: 0.7  # Higher threshold - only confident classifications

# Performance
max_tracks_per_frame: 9           # Expect fewer but stable tracks

# === EXPECTED IMPROVEMENTS WITH QUALITY-FOCUSED APPROACH ===
# 1. Track Count: 3-6 horses (instead of 83), 3-6 jockeys (instead of 178)
# 2. Track Persistence: Same track IDs throughout entire race
# 3. ReID Performance: High-confidence track recoveries when occlusion ends
# 4. SigLIP Success: Confident individual identification of tracked horses
# 5. Zero False Positives: Only track what we're confident about
# 6. Perfect for Race Analysis: Stable tracking of main contenders