# Pack Racing Optimized Configuration
# Tuned for tight pack formations with similar-looking horses
# Based on analysis of broadcast racing footage showing overlapping brown horses
# KEY GOAL: Stability over accuracy - prevent constant reassignments

# Scenario Information
scenario_name: pack_racing_optimized
expected_duration_seconds: 120
average_speed_mph: 35
camera_setup: broadcast_side_view
track_type: oval
notes: "Tight pack formation with similar brown horses - prioritize stability"

# Video and output settings
video_path: inputs/horse_11.mp4
output_path: null
display: false
device: cuda
max_frames: 1000

# Model selection
human_detector: rtdetr
horse_detector: rtdetr
human_pose_estimator: vitpose
horse_pose_estimator: superanimal
sam_model: sam2

# STRICTER confidence thresholds (reduce false detections in pack)
confidence_horse_detection: 0.7    # was 0.8, increase for pack racing
confidence_human_detection: 0.7     # was 0.7, increase
confidence_horse_pose_superanimal: 0.5  # was 0.6, increase
confidence_horse_pose_vitpose: 0.5
confidence_human_pose: 0.5

# MUCH STRICTER track stability (critical for pack racing)
track_stability_threshold: 0.8      # was 0.3, MUCH stricter for similar horses
track_newness_threshold: 15         # was 5, longer grace period for pack occlusions
initial_assignment_threshold: 0.8   # was 0.5, much harder initial assignment
reassignment_threshold: 0.95        # was 0.7, VERY hard to steal tracks in pack

# AGGRESSIVE stability controls (prevent oscillation in pack)
cooling_period: 30                  # was 10, triple the cooling time
oscillation_threshold: 1            # was 3, zero tolerance for oscillation
stability_bonus_factor: 0.4         # was 0.2, big bonus for stable tracks
stability_penalty_factor: 0.8       # was 0.5, big penalty for unstable tracks

# EXTENDED motion parameters for pack dynamics
motion_distance_threshold: 600      # was 200, much larger for pack position changes
max_motion_speed: 75.0             # was 30, higher for pack racing
motion_weight: 0.2                 # was 0.25, REDUCE (pack motion is chaotic)
motion_prediction_frames: 5        # was 3, longer prediction window

# MUCH LONGER memory for pack occlusions
samurai_memory_size: 40            # was 10, 4x longer for frequent occlusions
memory_cleanup_interval: 100       # was 50, cleanup much less frequently
track_expiry_frames: 200           # was 100, keep tracks alive much longer

# CONSERVATIVE quality monitoring for similar horses
quality_stability_window: 20       # was 10, longer window
confidence_variance_threshold: 0.1  # was 0.2, stricter confidence consistency
position_variance_threshold: 200   # was 100, allow more variance in pack

# STRICTER ByteTrack tuning for pack racing
bytetrack_track_activation_threshold: 0.8  # was 0.6, much stricter
bytetrack_lost_track_buffer: 100          # was 50, double the buffer
bytetrack_minimum_matching_threshold: 0.8  # was 0.6, much stricter
bytetrack_minimum_consecutive_frames: 5    # was 5, require consistency

# FEATURE weights optimized for similar horses in pack
visual_feature_weight: 0.3         # was 0.6, reduce (brown horses too similar)
motion_feature_weight: 0.2         # was 0.25, reduce (pack motion chaotic)
stability_feature_weight: 0.5      # was 0.15, MAJOR increase (stability is key)

# Enhanced ReID pipeline - more conservative
enable_reid_pipeline: true
reid_similarity_threshold: 0.5     # was 0.3, higher threshold for pack
enable_depth_anything: true

# SAM segmentation - conservative for overlapping horses
sam_multimask_output: false        # was true, single mask only (reduce confusion)
sam_confidence_threshold: 0.7      # was 0.5, require better masks
sam_center_point_weight: 1.0
sam_bbox_prompt_enabled: true

# STRICTER similarity calculation for similar horses
cosine_similarity_weight: 0.8      # was 0.7, rely more on cosine
l2_similarity_weight: 0.2         # was 0.3, reduce L2 weight

# Advanced feature extraction for pack racing
crop_padding_factor: 0.03          # was 0.05, less padding (reduce overlap)
min_crop_size: 60                  # was 50, slightly larger minimum
feature_vector_size: 64
color_histogram_bins: 6            # was 8, fewer bins (similar colors)

# Depth processing - more tolerant for pack
depth_weight: 0.25                 # was 0.3, reduce weight
depth_variance_threshold: 2000     # was 1000, much more tolerant
depth_normalization_range: 255

# Performance and limits
max_tracks_per_frame: 11
debug_logging: true
visualization_enabled: true
progress_bar_enabled: true

# PACK RACING SPECIFIC ADDITIONS
# New parameters for pack racing scenarios
pack_racing_mode: true             # Enable pack racing optimizations
similar_appearance_penalty: 0.3    # Penalty for high visual similarity
occlusion_tolerance: 0.8           # Higher tolerance for occlusions
track_persistence_bias: 0.4        # Bias toward keeping existing tracks

# Stability thresholds for pack racing
min_frames_before_reassignment: 10  # Minimum frames before allowing reassignment
max_reassignments_per_frame: 1      # Limit reassignments in pack scenarios
pack_density_threshold: 0.6         # Threshold for detecting pack formation

# Anti-fragmentation measures
fragmentation_prevention: true      # Enable anti-fragmentation features
track_consolidation_threshold: 0.9  # High threshold for track merging
duplicate_track_detection: true     # Enable duplicate detection