# Video file path (required)
video_path: inputs/horse_2.mp4

# Output settings
output_path: null  # Auto-generate if null
display: true

# Model selection
human_detector: rtdetr
horse_detector: rtdetr  # Options: rtdetr, superanimal ( NOT RECOMMENDED VERY SLOW )
human_pose_estimator: vitpose
horse_pose_estimator: superanimal # Options: superanimal (better), vitpose, both

# Separate confidence thresholds for each model
confidence_human_detection: 0.5
confidence_horse_detection: 0.5
confidence_human_pose: 0.5
confidence_horse_pose_superanimal: 0.5
confidence_horse_pose_vitpose: 0.5

# Other settings
jockey_overlap_threshold: 0.4
max_frames: null
device: cuda