# Enhanced 3D Pose Integration Configuration
# Advanced ReID with 3D pose features, GPU acceleration, and depth processing

# Basic Settings
video_path: inputs/horse_11.mp4
output_path: null
display: false
device: cuda
max_frames: 9000

# Model Selection
human_detector: rtdetr
horse_detector: rtdetr
human_pose_estimator: vitpose
horse_pose_estimator: superanimal
sam_model: sam2

# Confidence Thresholds
confidence_human_detection: 0.7
confidence_horse_detection: 0.8
confidence_human_pose: 0.5
confidence_horse_pose_superanimal: 0.5
confidence_horse_pose_vitpose: 0.5

# Basic Settings
jockey_overlap_threshold: 0.4

# Enhanced ReID Pipeline
enable_reid_pipeline: true
reid_similarity_threshold: 0.3

# Track Quality Monitoring
track_stability_threshold: 0.3    # Lower = more aggressive reassignment
track_newness_threshold: 5        # Frames to consider track "new"
quality_stability_window: 10      # Window for calculating stability

# Memory and Motion
samurai_memory_size: 10           # Memory size for track history
motion_distance_threshold: 200    # Motion prediction threshold (pixels)

# Components
enable_depth_anything: true

# ===== 3D POSE INTEGRATION =====
# Core 3D Processing
enable_3d_poses: true
enable_3d_reid_features: true
enable_gpu_acceleration_3d: true
enable_batch_processing_3d: true

# Depth Processing and Smoothing
depth_smoothing_algorithm: adaptive_gaussian  # 'gaussian', 'bilateral', 'adaptive_gaussian', 'none'
depth_smoothing_factor: 0.4
depth_temporal_smoothing: true
depth_temporal_window: 5
depth_outlier_threshold: 2.5      # Standard deviations for outlier removal
depth_noise_reduction_strength: 0.7

# Advanced Depth Quality Enhancement  
enable_depth_hole_filling: true
depth_hole_filling_method: inpaint  # 'inpaint', 'interpolation', 'nearest'
depth_edge_preservation: true
depth_edge_threshold: 12.0

# 3D Pose Quality Metrics
min_valid_keypoints_3d: 6
pose_3d_quality_threshold: 0.35
enable_geometric_consistency_check: true
geometric_plausibility_threshold: 0.65

# Enhanced 3D Geometric Features for ReID
enable_volumetric_features: true
enable_spatial_distribution_features: true
enable_depth_gradient_features: true
enable_pose_compactness_features: true
enable_temporal_3d_features: true

# 3D Feature Weighting for ReID (must sum to 1.0)
visual_feature_weight: 0.35
pose_3d_feature_weight: 0.30
geometric_feature_weight: 0.20
motion_weight: 0.10
stability_weight: 0.05

# GPU Acceleration Settings
gpu_batch_size_3d: 64              # Batch size for 3D processing
enable_gpu_depth_processing: true
enable_gpu_geometric_calculations: true
gpu_memory_optimization: true

# Performance Optimization
parallel_pose_processing: true
max_concurrent_poses: 12
enable_pose_caching: true
pose_cache_size: 50

# ===== 3D VISUALIZATION SETTINGS =====
# Depth Visualization
depth_visualization_scale: 5.0
pose_3d_transparency: 0.7
enable_depth_color_coding: true
show_3d_pose_quality: true

# 3D Display Options
show_depth_values: true
show_geometric_features: true
depth_color_scheme: jet            # 'jet', 'viridis', 'plasma', 'hot'
pose_3d_point_size_factor: 1.5

# ===== ADVANCED 3D PROCESSING =====
# Kalman Filtering for 3D Poses
enable_3d_kalman_filtering: true
kalman_process_noise: 0.08
kalman_measurement_noise: 0.4

# 3D Pose Temporal Consistency
enable_temporal_pose_smoothing: true
temporal_smoothing_window: 7
temporal_consistency_weight: 0.3

# Advanced Geometric Analysis
enable_pose_symmetry_analysis: true
enable_limb_length_consistency: true
limb_length_variance_threshold: 0.2

# Performance Settings
max_tracks_per_frame: 11          # Limit to expected number of horses

# ===== EXPERIMENTAL FEATURES =====
# These are advanced features that may impact performance
enable_pose_prediction: true      # Predict next frame pose
pose_prediction_window: 3
enable_multi_scale_depth: true    # Multi-resolution depth processing
enable_depth_attention: true      # Attention-based depth weighting